### ISSUE TITLE
libnotify alerts always disappears after 5 secs

### ISSUE THREAD

**Issue by emacsomancer** [jwiegley/alert#28]
No matter how I configure `alert-fade-time`, notifications always seem to disappear after 5 secs. I'm using libnotify on Linux.

E.g. I've set:

```
(setq alert-fade-time 3600)
```

But still the alerts disappear.

If I manually call `notify-send` from the commandline, I can pass through time specification without issue, e.g.:

```
notify-send -t 60000 "hello world" "goodbye world"
```

Works as expected.

**Comment by jwiegley** [comment]
Interesting; it sounds like we should be passing along the fade time to `notify-send`.

**Comment by emacsomancer** [comment]
Yes, that sounds like it would work.

**Comment by jwiegley** [comment]
@emacsomancer Would you be interested in crafting a patch, after signing a copyright assignment with the Emacs project? I'm working now to include `alert.el` into Emacs itself, and need those assignments to do so.

**Comment by emacsomancer** [comment]
@jwiegley I think it should be a fairly trivial patch; though my (e)lisp skills aren't great, but I've been wanting to improve those skills so this might be a good opportunity. Yes, I'm happy to sign the copyright assignment form.

**Comment by FrancisMurillo** [comment]
Isn't this just in `alert-libnotify-notify`?
```
        "--app-name" "Emacs"
                    "--hint" "int:transient:1"

                   ;; HACK: Extra expire time
                    "--expire-time" (let ((fade-time (if (numberp alert-fade-time)
                                                         alert-fade-time
                                                       (car (get 'alert-fade-time 'standard-value))
                                                       )))
                                      (number-to-string (* 1000 fade-time)))
```

**Comment by termlen0** [comment]
Hello,
I was running into this same issue and came across an old open issue here. Was wondering if there is an update..

**Comment by emacsomancer** [comment]
It's a trivial fix. I have a pull request open (see https://github.com/jwiegley/alert/pull/31 ), but because `alert` is/was/has been (?) integrated as a core emacs package, I needed to assign copyright to the FSF, which I did, but they also wanted a letter from my employer which I was unable to get (despite spending many hours of writing explanations and responding to objections).   

As I said, the actual fix is trivial - you can look at the pull request to see how trivial it is. (I'm happy for someone else to implement a fix - I hope to resolve the copyright assignment issue eventually, but who knows how long that may take).

**Comment by bandresen** [comment]
@jwiegley I would like to have this fixed upstream as well.

Anything I can do to get the PR by @emacsomancer merged? I could rewrite it. I have assigned copyright to the FSF in 2006 or so for Emacs Org-Mode. :-)

**Comment by jwiegley** [comment]
Can you rewrite it without reading it?

**Comment by bandresen** [comment]
I fixed it on my local copy before I looked for an existent issue. So I wrote it without reading any other code.
