### ISSUE TITLE
Incompatibility with emacs 25.1

### ISSUE THREAD

**Issue by krazedkrish** [jwiegley/alert#43]
Hi! I am an emacs user using spacemacs and org-pomodoro which happen to use alert. I didn't receive notificaitons from org-pomodoro because. I am not good with elisp but my hunch is alert is not compatible with emacs 25.1. I kindly request for the compatibility with this one thanks.

**Comment by adicarlo** [comment]
I'm not the developer but it might be helpful to include relevant output, if any, from the *Messages* buffer.

I might be having the same issue, but in my case the *Messages* buffer looks like:

(alert "hello")
==> *Messages*
hello
[nil 22763 38821 70584 nil alert-remove-when-active (alert-message-remove (:message "hello" :title "*scratch*" :icon nil :severity normal :category nil :buffer #<buffer *scratch*> ...)) nil 718000]

**Comment by krazedkrish** [comment]
Hi! @adicarlo,
Thanks for the response.
I will include the Message buffer next time.

For now the issue is solve.
Thanks for all of you for this amazing library, and for solving it.

😄

**Comment by dcorking** [comment]
@adicarlo did you solve your issue? I too see nothing in the minibuffer or the mode line.  When I eval

    (alert "foo")

`*Messages*` shows
```elisp
foo
[nil 22812 27061 399832 nil alert-remove-when-active (alert-message-remove (:message "foo" :title "*scratch*" :icon nil :severity normal :category nil :buffer #<buffer *scratch*> ...)) nil 0]
```

My versions:
```
;; Updated: 16 Mar 2015
;; Version: 1.2
;; Package-Version: 20160824.821
    GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org
```

@adicarlo If you don't know the answer, lets open a new ticket to discuss this.

**Comment by adicarlo** [comment]
No, I get the same behavior you do, @dcorking .  I encourage you to split off a ticket or whatever is appropriate!
