### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by thblt** [jwiegley/alert#46]
Version 1.2 is almost two years and 22 commits old, including some important bug fixes (Eg, 80374afedc1b99c283ea2a66327fa2d52e43bdfd). Could you please tag a release, so that people who get alert from melpa-stable get the bugfixes?

Also, since Emacs 25.x now has `package-archive-priorities`, tagged releases for all packages are not needed anymore for people who prefer Melpa Stable.  Hence, deleting *all* the release tags is also an option, alert will then be removed from stable, but properly configured recent Emacs will be able to fallback to Melpa.  (Alhough I can't confirm deleting tags is enough to remove a package from Melpa Stable, I believe it can be safely assumed.)

Thanks a lot,
Thibault

**Comment by jwiegley** [comment]
I think that `alert` doesn't even notify right now on some platforms. I'd like to get those issues fixed before the next release.

**Comment by unhammer** [comment]
What issues are remaining before 1.3 can be released? I'd like to depend on 1.3 in https://github.com/unhammer/org-random-todo/ for `:id` support :)

**Comment by jwiegley** [comment]
I'll tag a new release today.

**Comment by jwiegley** [comment]
Tagged and pushed `v1.3`.
