### ISSUE TITLE
alert won't notify via notify-send

### ISSUE THREAD

**Issue by pseudomyne** [jwiegley/alert#74]
Arch linux here, with `dunst` as a notification manager. My notifications problems are emacs-related only because `notify-send "wow"` works from a terminal. Still, I get desktop notifications in emacs with `(notifications-notify :title "You've got mail!").`But not with `(alert "This is an alert")`, neither with `mu4e` nor `circe`. 
`(alert--log-open-log) ` sends no particular errors. 
 
I think I have tweaked something bad somewhere because at least, mu4e used to notify my new mail. Alas, I've totally lost my memory about that. Any idea ?

**Comment by pseudomyne** [comment]
Seems to work now, but I'm still unsure of why. Finally, (`setq alert-default-style 'libnotify)` might have been unset. And /or Customize `Alert Libnotify Command` had been temporarily put (by myself, while trying to resolve the issue) to something else than `/usr/bin/notify-send `...

**Comment by jcguu95** [comment]
Thanks for pointing this out! It allowed me to pin down the issue, which is reported in https://github.com/jwiegley/alert/issues/92.
